config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :caregivers
  resources :fammembers

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :conditions, as: :sconditions
  has_many :users, as: :usertypes, dependent: :destroy
  has_many :locations, as: :geographies, dependent: :destroy
  has_many :languages, as: :sglangs, dependent: :destroy
  has_many :frequencies, as: :occurences, dependent: :destroy

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password, length: {in: 8..72}, on: :create

  validates :contact, length: {is: 8},
  presence: true

  has_secure_password


  searchable do
    integer :id
    text :first_name, boost: 5.0
    text :last_name, boost: 5.0
    integer :yearsofexperience
    text :experiencedescription
  end

  def self.find_and_authenticate(params)
    Caregiver.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :sconditions, polymorphic:true

  searchable do
    text :name, boost: 5.0
  end
end

app/models/fammember.rb
class Fammember < ApplicationRecord
  has_many :users, as: :usertypes
  before_save {self.email = email.downcase}
  has_many :patients

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password, length: {in: 8..72}, on: :create

  validates :contact, length: {is: 8},
  presence: true


  has_secure_password

  def self.find_and_authenticate(params)
    Fammember.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/models/frequency.rb
class Frequency < ApplicationRecord
  belongs_to :occurences, polymorphic:true

  searchable do
    text :name, boost: 5.0
  end
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :sglangs, polymorphic:true

  searchable do
    text :name, boost: 5.0
    
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :geographies, polymorphic:true

  searchable do
    text :name, boost: 5.0

  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :fammember
  has_many :conditions, as: :sconditions, dependent: :destroy
  has_many :locations, as: :geographies, dependent: :destroy
  has_many :languages, as: :sglangs, dependent: :destroy
  has_many :frequencies, as: :occurences, dependent: :destroy

  searchable do
    integer :id
    text :condition_description
  end
   
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  before_save {self.email = email.downcase}

  belongs_to :fammember
  belongs_to :patient
  belongs_to :caregiver

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :usertypes, polymorphic:true, dependent: :destroy

end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController
  before_action :set_caregiver, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @caregiver = Caregiver.new
  end

  def create
    @caregiver = Caregiver.new(caregiver_params)
    if
      @caregiver.save
      redirect_to @caregiver, notice: "Your profile has been sucessfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @caregiver= Caregiver.update(fammember_params)
  end

  def destroy
    @caregiver.destroy
    redirect_to caregivers_url
  end

  private

  def set_caregiver
    @caregiver = Caregiver.find(params[:id])
  end

  def caregiver_params
    params.require(:caregiver).permit(:first_name, :last_name, :contact, :email, :password, :gender, :certification, :yearsofexperience, :experiencedescription, :photo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/careseekers_helper.rb
module CareseekersHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
  conditions = ['Clinical Procedures', 'Nursing Care', 'General Care']
end

app/helpers/fammembers_helper.rb
module FammembersHelper
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
  frequencies = ['daily', 'weekly', 'monthly', 'one-off', 'others']
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
  languages = ['chinese','english','hakka', 'hindi','hokkien','malay','tamil','teochew']
end

app/helpers/locations_helper.rb
module LocationsHelper
  locationsstr = 'Bedok Tampines
  Woodlands
  JurongWest
  Tampines
  Woodlands
  Hougang
  Sengkang
  Yishun
  AngMoKio
  ChoaChuKang
  BukitMerah
  BukitBatok
  BukitPanjang
  ToaPayoh
  Serangoon
  Geylang
  Punggol
  Kallang
  Queenstown
  Clementi
  PasirRis'

  locations = locationsstr.split(' ')
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/caregivers/_form.html.erb
<%= bootstrap_form_for(@caregiver) do |f| %>
  <% if @caregiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize( @caregiver.errors.count, "error") %> prohibited this caregiver from being saved:</h2>

      <ul>
      <% @caregiver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.string_field :first_name %>
  </div>

  <div>
    <%= f.string_field :last_name %>
  </div>

  <div>
    <%= f.string_field :email %>
  </div>

  <div>
    <%= f.integer_field :contact %>
  </div>

  <div>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.string_field :gender %>
  </div>

  <div>
    <%= f.string_field :certification %>
  </div>

  <div>
    <%= f.text_field :experiencedescription %>
  </div>

  <div>
    <%= f.string_field :photo %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/caregivers/index.html.erb
<h1>Hi there care giver</h1>
<center><button type = "button" class = "btn btn-default"><%= link_to 'Join Us', new_caregiver_path %></button></center>
<center><button type = "button" class = "btn btn-default"><%= link_to 'Login', login_url %></button></center>

<%= link_to 'Back', root_path %>

app/views/caregivers/new.html.erb
<h1>Caregiver Sign Up Page</h1>
<%= render 'form' %>

app/views/caregivers/show.html.erb
<button>Join Us</button>